---
# Configure the apache webserver
- name: configure apache
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: '000-default.conf', dest: '/etc/apache2/sites-enabled/000-default.conf' }
    - { src: 'index.html', dest: '/var/www/html/index.html' } 
