---
#- hosts: ansible02
#  roles:
#    - apache
#    - ntp

- hosts: ubuntu01
  roles:
    - role: default
      become: yes
    - role: apache
      become: yes
    - role: mysql
      become: yes

- hosts: ubuntu02
  roles:
    - role: default
      become: yes
    - role: apache
      become: yes
    - role: mysql
      become: yes

